const DEMO={brand:{name:'Oaza Coffee',tagline:'قهوة مختصة • الرياض',logo:'O',maps:'https://maps.google.com/?q=Oaza+Coffee+Riyadh',instagram:'https://instagram.com/oaza.ksa',whatsapp:'https://wa.me/966566332329'},categories:[
{id:'hot',ar:'القهوة الساخنة',en:'Hot Coffee',icon:'☕'},{id:'cold',ar:'القهوة الباردة',en:'Cold Coffee',icon:'🧊'},{id:'drip',ar:'القهوة المقطرة',en:'Drip Coffee',icon:'◌'},{id:'tea',ar:'الشاي والماتشا',en:'Tea & Matcha',icon:'🍵'},{id:'mojito',ar:'موهيتو ومشروبات',en:'Mojito & Drinks',icon:'✦'},{id:'dessert',ar:'الحلويات',en:'Desserts',icon:'🍰'},{id:'bakery',ar:'المخبوزات',en:'Bakery',icon:'🥐'},{id:'retail',ar:'حبوب القهوة',en:'Coffee Beans',icon:'◉'}],items:[
[1,'hot','إسبريسو','Espresso','جرعة مركزة بطابع غني ومتوازن',12,'☕',true,true],[2,'hot','كورتادو','Cortado','إسبريسو مع كمية متوازنة من الحليب الدافئ',14,'☕',true,false],[3,'hot','فلات وايت','Flat White','إسبريسو مزدوج مع حليب مبخر ناعم',16,'☕',true,true],[4,'hot','لاتيه','Latte','إسبريسو مع حليب مبخر ورغوة ناعمة',17,'☕',true,false],[5,'hot','كابتشينو','Cappuccino','إسبريسو مع الحليب ورغوة كريمية',17,'☕',true,false],[6,'hot','سبانيش لاتيه','Spanish Latte','إسبريسو، حليب وحليب مكثف بنكهة غنية',18,'☕',true,true],[7,'hot','أمريكانو','Americano','إسبريسو ممزوج بالماء الساخن',13,'☕',true,false],[8,'hot','هوت تشوكلت','Hot Chocolate','كاكاو غني مع حليب مبخر',15,'☕',true,false],
[9,'cold','آيس لاتيه','Iced Latte','إسبريسو وحليب بارد فوق الثلج',18,'🧊',true,true],[10,'cold','آيس سبانيش لاتيه','Iced Spanish Latte','إسبريسو، حليب وحليب مكثف بارد',19,'🧊',true,true],[11,'cold','آيس بستاشيو','Iced Pistachio Latte','لاتيه بارد بلمسة فستق ناعمة',19,'🧊',true,false],[12,'cold','آيس وايت موكا مع كراميل','Iced White Mocha Caramel','إسبريسو، شوكولاتة بيضاء وحليب وكراميل',20,'🧊',true,false],[13,'cold','آيس موكا','Iced Mocha','إسبريسو مع الشوكولاتة والحليب والثلج',19,'🧊',true,false],[14,'cold','آيس أمريكانو','Iced Americano','إسبريسو وماء بارد مع الثلج',14,'🧊',false,false],
[15,'drip','V60 إندونيسيا','V60 Indonesia Java','قهوة مقطرة تبرز النكهات الطبيعية للمحصول',20,'◌',true,true],[16,'drip','V60 إثيوبيا','V60 Ethiopian','محصول إثيوبي محضر بالتقطير',19,'◌',true,false],[17,'drip','V60 Colombia','V60 Colombia Sanchz','قهوة مقطرة من كولومبيا',22,'◌',true,false],[18,'drip','بوكس القهوة','Coffee Box','اختيار مناسب للمشاركة والمناسبات',35,'▣',true,false],
[19,'tea','أوزا ماتشا','Oaza Matcha','ماتشا كريمية بنكهة متوازنة',19,'🍵',true,true],[20,'tea','ستروبيري ماتشا','Strawberry Matcha','ماتشا مع الفراولة والحليب',20,'🍵',true,true],[21,'tea','شاهي إبريق صغير','Small Tea Pot','شاي ساخن يقدم في إبريق صغير',15,'🍵',true,false],[22,'tea','كركديه كبير','Large Hibiscus Tea','كركديه بارد منعش بنكهة زهرية',14,'🍵',true,false],
[23,'mojito','ليموناضة نعناع','Mint Lemonade','ليمون، نعناع ولمسة زنجبيل منعشة',15,'✦',true,false],[24,'mojito','موهيتو بطيخ','Watermelon Mojito','بطيخ طازج، نعناع، لايم ومياه غازية',17,'✦',true,true],[25,'mojito','ستروبيري موهيتو','Strawberry Mojito','فراولة، ليمون، نعناع ومياه غازية',17,'✦',true,false],[26,'mojito','موهيتو كلاسيك','Classic Mojito','ليمون ونعناع بطابع كلاسيكي',15,'✦',true,false],
[27,'dessert','براونيز','Brownies','براونيز شوكولاتة بلمسة مالحة',10,'🍰',true,false],[28,'dessert','كوكيز','Cookies','كوكيز شوكولاتة بلمسة مالحة',10,'🍪',true,false],[29,'dessert','فرنش توست كلاسيك','Classic French Toast','بريوش محمص مع خيارات من الشراب والفواكه',19,'🍰',true,true],[30,'dessert','مانجو تشيزكيك','Mango Cheesecake','تشيزكيك كريمي مع المانجو',21,'🍰',false,false],[31,'dessert','تيراميسو','Tiramisu','طبقات إسبريسو وماسكربوني مع الكاكاو',21,'🍰',false,false],
[32,'bakery','كرواسون سادة','Plain Croissant','كرواسون زبدة هش ومخبوز يوميًا',9,'🥐',true,false],[33,'bakery','كرواسون جبنة','Cheese Croissant','كرواسون هش بحشوة الجبن',11,'🥐',false,false],[34,'bakery','كرواسون باللوز','Almond Croissant','كرواسون بحشوة اللوز وشرائح اللوز المحمصة',13,'🥐',false,false],
[35,'retail','Ethiopia Chelchelectu 250g','Ethiopia Chelchelectu 250g','حبوب قهوة مختصة 250g',55,'◉',true,false],[36,'retail','Brazil Fernando 250g','Brazil Fernando 250g','حبوب قهوة مختصة 250g',39,'◉',true,false],[37,'retail','Colombia Castro 250g','Colombia Castro 250g','حبوب قهوة مختصة 250g',69,'◉',true,false],[38,'retail','Ethiopian Coffee Drip Bag','Ethiopian Coffee Drip Bag','أكياس قهوة مقطرة جاهزة',32,'◉',true,false]
].map(x=>({id:x[0],cat:x[1],ar:x[2],en:x[3],desc:x[4],price:x[5],icon:x[6],available:x[7],featured:x[8]}))};
let data=DEMO,lang=localStorage.getItem('menuLang')||'ar',active='all',query='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function itemMatches(x){const q=query.trim().toLowerCase();return !q||`${x.ar} ${x.en} ${x.desc}`.toLowerCase().includes(q)}
function render(){const ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';const cats=[{id:'all',ar:'الكل',en:'All',icon:'✦'},...data.categories];const filtered=data.items.filter(x=>(active==='all'||x.cat===active)&&itemMatches(x));document.getElementById('brandName').textContent=ar?data.brand.name:data.brand.name;document.getElementById('brandTagline').textContent=ar?data.brand.tagline:'Specialty coffee, desserts & fresh bakery.';document.getElementById('langBtn').textContent=ar?'EN':'عربي';document.getElementById('itemCount').textContent=`${filtered.length} ${ar?'منتج':'items'}`;document.getElementById('categoryNav').innerHTML=cats.map(c=>`<button class="cat ${active===c.id?'active':''}" data-cat="${c.id}">${c.icon} ${ar?c.ar:c.en}</button>`).join('');const featured=filtered.filter(x=>x.featured&&x.available).slice(0,3);document.getElementById('featured').innerHTML=featured.length?`<div class="featured-title"><span>${ar?'اختياراتنا':'Editor picks'}</span></div><div class="featured-row">${featured.map(x=>`<button class="featured-card" data-item="${x.id}"><span class="item-icon">${x.icon}</span><span><b>${ar?x.ar:x.en}</b><small>${x.price} SAR</small></span></button>`).join('')}</div>`:'';const groups=active==='all'?data.categories:data.categories.filter(c=>c.id===active);document.getElementById('menuList').innerHTML=groups.map(c=>{const arr=filtered.filter(x=>x.cat===c.id);if(!arr.length)return '';return `<section class="menu-section"><div class="section-head"><div><p class="eyebrow">${c.en}</p><h2>${ar?c.ar:c.en}</h2></div><span>${arr.length}</span></div><div class="item-grid">${arr.map(x=>`<button class="menu-item ${x.available?'':'unavailable'}" data-item="${x.id}"><span class="item-icon">${x.icon}</span><span class="item-copy"><b>${ar?x.ar:x.en}</b><small>${ar?x.desc:x.en}</small><em>${x.available?`${x.price} SAR`:ar?'غير متوفر':'Unavailable'}</em></span><span class="chev">‹</span></button>`).join('')}</div></section>`}).join('');document.getElementById('emptyState').classList.toggle('hidden',filtered.length>0);document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{active=b.dataset.cat;render()});document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>openItem(Number(b.dataset.item)));}
function openItem(id){const x=data.items.find(i=>i.id===id);if(!x)return;const ar=lang==='ar',c=data.categories.find(c=>c.id===x.cat);document.getElementById('modalCategory').textContent=ar?c.ar:c.en;document.getElementById('modalTitle').textContent=ar?x.ar:x.en;document.getElementById('modalDescription').textContent=ar?x.desc:x.en;document.getElementById('modalMeta').innerHTML=x.available?'<span>✓ متوفر</span><span>15% VAT included</span>':'<span>غير متوفر حاليًا</span>';document.getElementById('modalPrice').textContent=`${x.price} SAR`;document.getElementById('modalImage').textContent=x.icon;document.getElementById('itemModal').classList.remove('hidden');}
document.getElementById('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('menuLang',lang);render()};document.getElementById('searchInput').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>document.getElementById('itemModal').classList.add('hidden'));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('itemModal').classList.add('hidden')});render();